### ISSUE TITLE
identificador global duplicado no RDF TipoDocumento

### ISSUE THREAD

**Issue by ppKrauss** [lexml/lexml-vocabulary#5]
Identificadores globais `rdf:id` (aparecem como `<skos:Concept rdf:id="123">`) não podem ser duplicados dentro de um mesmo arquivo `.rdf.xml`. 

Já na versão v1.0.0 do vocabulário de TipoDocumento aparecia o  `rdf:id="461"` duas vezes. 

Solução: trocar a segunda ocorrência de 461 por 3000. Na v1.0.0 são o *max(rdf:id)* é 2381, então pode-se eleger do 3000 em diante como ID seguro para novos itens.

**Comment by joaoli13** [comment]
@ppKrauss , existia uma inconsistência num label alternativo... Fiz o ajuste... Amanhã, após a sincronização, acho que o identificador duplicado irá desaparecer... vamos conferir....

**Comment by joaoli13** [comment]
@ppKrauss , a inconsistência parece que foi sanada em http://www.lexml.gov.br/vocabulario/tipoDocumento.rdf.xml 

Acho que podemos fechar esse issue...

**Comment by ppKrauss** [comment]
Ok, normalizei seu XML e substitui no git... Subindo em seguida, o próprio commit com a palavra "close" vai fechar aqui.
