### ISSUE TITLE
Atributo lexml:urnAlt de Localidade precisa de separador

### ISSUE THREAD

**Issue by ppKrauss** [lexml/lexml-vocabulary#7]
O valor do atributo *urnAlt* em  `<skos:altLabel lexml:urnAlt="brac" ...>` precisa ser `br;ac`, com separador ";" antes de "br".

Exemplo extraído do vocabulário de Localidade:

```xml
  <skos:Concept rdf:about="br;acre" rdf:id="20">
    <skos:prefLabel lexml:faceta="Estados::Acre" lexml:facetaAcronimo="AC – Acre"
     rdf:nodeID="label_77"  xml:lang="pt-BR">Acre</skos:prefLabel>
    <skos:altLabel lexml:acronimoDe="label_77" lexml:urnAlt="brac" rdf:nodeID="label_78" 
     xml:lang="pt-BR">AC</skos:altLabel>
    <skos:inScheme rdf:resource="#localidade"/>
    <skos:broader rdf:resource="#br"/>
</skos:Concept>
```

**Comment by joaoli13** [comment]
Essa correção deve ser feita no programa que exporta o arquivo de vocabulário... farei por aqui....

**Comment by ppKrauss** [comment]
Oi @joaoli13, ótimo (!).  E onde vai aparecer esse novo XML exportado por você? Seria no mesmo http://dadosabertos.senado.leg.br/dataset/vocabul-rios-controlados-da-urn-lex  ?

Qualquer que seja o local, só avisar que eu filtro e atualizo aqui no nosso git, como fiz no  [preparo dos XMLs   da v1.0.1](https://github.com/lexml/lexml-vocabulary/blob/master/docs/preparo/v1.0.1.md#arquivos-xml).

**Comment by joaoli13** [comment]
Sim, são naqueles endereços indicados lá...

Fiz o ajuste hoje. Acho que aparecerá amanhã a partir das 14h00.

Abs

Joao

2017-11-22 16:07 GMT-02:00 Peter <notifications@github.com>:

**Comment by joaoli13** [comment]
Verifiquei que o arquivo http://www.lexml.gov.br/vocabulario/localidade.rdf.xml está correto em relação a essa issue. Acho que podemos fechar essa issue.

**Comment by ppKrauss** [comment]
Oi @joaoli13  eu baixei o XML do seu link e reparei que está mesmo diferente da versão original [`localidade.rdf.xml` v1.0.0](https://raw.githubusercontent.com/lexml/lexml-vocabulary/v1.0.0/data/RDF-v1.0/localidade.rdf.xml)... Então [normalizei](https://github.com/lexml/lexml-vocabulary/blob/master/docs/preparo/v1.0.1.md#arquivos-xml) o seu arquivo XML e subi aqui pro *git*: onde [você pode **ver as diferenças**](https://github.com/lexml/lexml-vocabulary/commit/595fd03363628c7847f4665065d9661a57d46c8c#diff-cd2ddc9f10f07a11f49c0d4062fd7351).

Fechado.

----

Para futuras alterações, mesmo que tomemos [aqui](https://github.com/lexml/lexml-vocabulary/releases) como "versão oficial", acho importante manter o CKAN do do *dadosabertos.senado.leg.br*  sincronizado... Ficou estranho na página 

http://dadosabertos.senado.leg.br/dataset/vocabul-rios-controlados-da-urn-lex/resource/0c3ebdb9-8bc7-48e2-a99a-5da29434699c

pois não atualizou o *revision_timestamp*. Também senti falta do o atributo *hash*, vale a pena pedir para os mantenedores do CKAN habilitarem.  Sem o hash não posso conferir se estamos sincronizados.

PS: por isso me apressei em subir e discutir só esse arquivo, antes de lançar a versão v1.0.2 com todas as alterações de hoje.
