### ISSUE TITLE
voc. lingua, nome oficial do Português do Brasil

### ISSUE THREAD

**Issue by ppKrauss** [lexml/lexml-vocabulary#9]
A sigla *pt-br* designa [*Português do Brasil*](https://www.wikidata.org/wiki/Q750553), não é apenas Português (genérico). Sugere-se corrigir o seu `skos:prefLabel`.

----

PS1: quanto ao uso do `<skos:inScheme rdf:resource="#lingua"/>` neste e em outros vocabulários, me parece redundante, visto que uma das regras fundamentais de qualquer XML é a herança: se nada é dito contrário, o elemento herda o atributo. A regra da herança também deveria ser usada para subintender o `xml:lang` (o idioma no qual são expressas as descrições e nomenclaturas).  

PS2: quanto às regras discutidas em #6, convém limitar aos idiomas previamente definidos neste vocabulário, assim como explicitar o link entre eles.

**Comment by joaoli13** [comment]
Como as questões de conceitos/instituições jurídicas são muito dependentes de jurisdição, será que não seria melhor manter o “pt-BR” justamente para diferenciar de um termo utilizado em outro país que adote a língua portuguesa mas outro termo? Por exemplo, imagine que o conceito de “súmula” no Brasil seja equivalente ao conceito de “enunciado” em Portugal. Na configuração atual, poderíamos ter dois labels preferidos, não?

Reply to PS1:  parece que é uma boa prática sempre especificar o inScheme ( de: https://wiki.dca-project.eu/wiki/SKOS - For every concept that must be part of a concept scheme, a formal assertion is needed stating that the concept belongs to the concept scheme. ) Apenas no caso de especificação de TopConcept (como é uma especialização de inScheme) não seria necessário especificar o inScheme.  

Reply2 to PS1: como o atributo xml:lang é herdado pelo subelementos, parece ser interessante remover a duplicação dele... vou estudar mais sobre isso.

Reply to PS2:  Não entendi direito... como fazer isso?

**Comment by ppKrauss** [comment]
Olá  @joaoli13 , quanto à correção, desculpe, é isso mesmo, coloquei "Sugere-se corrigir o seu skos:prefLabel" faltou o recheio, é corrigir o label para `<skos:prefLabel>Português do Brasil</skos:prefLabel>` . Feito (!).

-----

Quanto aos PS's.  

* faltou eu  explicar melhor relação entre o uso do `lang` nos vocabulários, e o compromisso como chave-estrangeira.... É apenas sugestão de obrigar (criar regra) que, sempre que alguém usar em algum vocabulário alguma `lang`, esse valor de `lang` precisa estar presente no `lingua.rdf.xml`, que [por hora são apenas 6](https://github.com/lexml/lexml-vocabulary/blob/master/data/lingua.csv), não todas as [722](https://github.com/datasets/language-codes/blob/master/data/ietf-language-tags.csv).

* Sugiro usar como referência as comunidades XML ativas e os mais atualizados. SKOS tem pouco uso e a [wiki é de 2013](https://wiki.dca-project.eu/index.php?title=SKOS&action=history)... Gosto do [JATS](https://jats.nlm.nih.gov/publishing/tag-library/1.2d1/index.html), que tem uma grande comunidade e grandes editoras usando... Nos XMLs modernos parece consenso que a herança (subintender a propagação de atributos gerais como `lang` e `resource` aos elementos-filho) é a melhor prática... Mas não é obrigação.
